#!/bin/bash
set -e
source _common

ENSURE LDLK_WORKDIR
ENSURE LDLK_INSTANCE

../base/init

EXISTS $GCLOUD || \
    (ERROR "gcloud is not installed. Please install from https://cloud.google.com/sdk/downloads"; false)

INFO "Validating gcloud configuration"
# TODO: use jq for faster execution?
test ! -z $($GCLOUD -q config list --format 'value(core.project)') || \
    (ERROR "core.project not set. Please try: gcloud config set compute core/project PROJECT."; false)
test ! -z $($GCLOUD -q config list --format 'value(compute.region)') || \
    (ERROR "compute.region not set. Please try: gcloud config set compute/region REGION (e.g.asia-east1)."; false)
test ! -z $($GCLOUD -q config list --format 'value(compute.zone)') || \
    (ERROR "compute.zone not set. Please try: gcloud config set compute/zone ZONE (e.g.asia-east1-c)."; false)

$GCLOUD compute ssh $UZER@$LDLK_INSTANCE -- sudo groupadd -f docker
