#!/bin/bash
set -e
source _common

ENSURE LDLK_WORKDIR
ENSURE LDLK_INSTANCE

EXISTS docker || \
    (ERRROR "docker is not installed (needed for building docker itself)")

if [ ! -d $LDLK_WORKDIR/$LDLK_INSTANCE ]; then
    INFO "Creating $LDLK_WORKDIR/$LDLK_INSTANCE"
    mkdir -p $LDLK_WORKDIR/$LDLK_INSTANCE
fi
